---
title: "Simulation"
author: "Sunsik Kim"
output: pdf_document
---
```{r echo=FALSE}
source("normaldpm_lmm.R")
source("normalbsa_lmm.R")
source("normalbsadpm_lmm.R")
source("../misc/make_Z.R")
```

## Simulation size setting
```{r}
set.seed(10); R = 10 # R : Truncation level
N = 50; T = 4; D = 7
Z = make_Z(rep(T, N))
```

# Normal DPM in LMM

## Data generation
```{r}
beta = rnorm(D+1)
w = matrix(rnorm(N*T*D), N*T, D)
# Represent random intercept as mixture of 3 normal distributions
assigner = runif(N)
mu1 = 3; mu2 = 0; mu3 = -3
u = rnorm(N, mu1, 0.49)
u[assigner > 0.33] = rnorm(sum(assigner > 0.33), mu2, 0.49)
u[assigner > 0.66] = rnorm(sum(assigner > 0.66), mu3, 0.49)
y = cbind(1, w)%*%beta + Z%*%u + rnorm(nrow(Z))
```

## Result presentation
```{r echo=FALSE, fig.height=3.8, fig.width=8, fig.align="center"}
start = as.numeric(Sys.time())
result = normaldpm_lmm(y,w,Z,R) # truncate at R=10
print(paste(round(as.numeric(Sys.time())-start, 4), "seconds elapsed."))
par(mfrow=c(1,2))
plot(beta[-1], result$mubeta.q[-1], main="Fixed effects", xlab="True", ylab="Estimated")
lines(-10:10, -10:10)
plot(u, result$muu.q, main="Random intercepts", xlab="True", ylab="Estimated")
lines(-10:10, -10:10)
```

# Normal DPM in BSA-LMM

## Data generation
```{r}
beta = rnorm(D+1)
w = matrix(rnorm(N*T*D), N*T, D)
f = function(x) -3*(x-1.5)^4
x = 3*runif(N*T); ord = order(x)
```

## Generating random intercepts
```{r}
# Ordinary LMM
u_lmm = rnorm(N)
y_lmm = cbind(1, w)%*%beta + Z%*%u_lmm + f(x) + rnorm(nrow(Z))
# DPM : Represent random intercept as mixture of 3 normal distributions
assigner = runif(N)
mu1 = 3; mu2 = 0; mu3 = -3
u_dpm = rnorm(N, mu1)
u_dpm[assigner > 0.33] = rnorm(sum(assigner > 0.33), mu2)
u_dpm[assigner > 0.66] = rnorm(sum(assigner > 0.66), mu3)
y_dpm = cbind(1, w)%*%beta + Z%*%u_dpm + f(x) + rnorm(nrow(Z))
```

## Result presentation
```{r echo=FALSE, fig.height=5, fig.width=8, fig.align="center"}
start = as.numeric(Sys.time())
result_lmm = normalbsa_lmm(y_lmm,x,w,Z,23)
result_dpm = normalbsadpm_lmm(y_dpm,x,w,Z,23,R) # truncate at R=10
print(paste(round(as.numeric(Sys.time())-start, 4), "seconds elapsed."))
par(mfrow=c(2,2))
plot(beta[-1], result_lmm$mubeta.q[-1], main="Fixed effects(BSA-LMM)", xlab="True", ylab="Estimated")
lines(-10:10, -10:10)
plot(u_lmm, result_lmm$muu.q, main="Random intercepts(BSA-LMM)", xlab="True", ylab="Estimated")
lines(-10:10, -10:10)
plot(beta[-1], result_dpm$mubeta.q[-1], main="Fixed effects(BSA-DPM)", xlab="True", ylab="Estimated")
lines(-10:10, -10:10)
plot(u_dpm, result_dpm$muu.q, main="Random intercepts(BSA-DPM)", xlab="True", ylab="Estimated")
lines(-10:10, -10:10)
```

```{r echo=FALSE, fig.height=8, fig.width=8, fig.align="center"}
par(mfrow=c(2,1))
res_lmm = y_lmm-(cbind(1,w)%*%result_lmm$mubeta.q - Z%*%result_lmm$muu.q)
res_dpm = y_dpm-(cbind(1,w)%*%result_dpm$mubeta.q - Z%*%result_dpm$muu.q)
plot(x,res_lmm, main="Fitted mean curve(BSA-LMM)", ylab="")
lines(x[ord],result_lmm$post_curve[ord],lwd=3,col=3)
lines(x[ord],result_lmm$post_lower[ord],lwd=2,lty=2)
lines(x[ord],result_lmm$post_upper[ord],lwd=2,lty=2)
plot(x,res_dpm, main="Fitted mean curve(BSA-DPM)", ylab="")
lines(x[ord],result_dpm$post_curve[ord],lwd=3,col=3)
lines(x[ord],result_dpm$post_lower[ord],lwd=2,lty=2)
lines(x[ord],result_dpm$post_upper[ord],lwd=2,lty=2)
```