---
title: "Simulation"
author: "Sunsik Kim"
output:
  pdf_document: default
---

```{r}

pathlist = c("../misc/wandint.R", "../misc/make_Z.R", 
             "vbsf_exp.R", "vbsf_gam.R", "vbbsasf_exp.R", "vbbsasf_gam.R")
for (path in pathlist) source(path)
```

```{r}
n = 50
ti = 4; D = 10
Z = make_Z(rep(ti, n))
sigma = 0.8
lambda = 0.7
```

# Exponential inefficiency

## Linear
```{r}
set.seed(10)
betaT = rnorm(D+1)
w = matrix(rnorm(nrow(Z)*D), ncol=D)
uT = rexp(n,lambda)
y = drop(cbind(1,w)%*%betaT-rep(uT,each=ti)+rnorm(nrow(Z),sd=sigma))
start = as.numeric(Sys.time())
result = vbsf_exp(y,w,Z)
print(paste("Time elapsed :", round(as.numeric(Sys.time()-start),4), "seconds"))
```

```{r echo=FALSE,fig.align="center",fig.height=3.7,fig.width=7}
par(mfrow=c(1,2))
plot(betaT,result$mubeta.q,main="Fixed effect",xlab="True",ylab="Estimated")
lines(-10:10,-10:10)
plot(uT,result$muu.q,main="Inefficiency",xlab="True",ylab="Estimated")
lines(-10:10,-10:10)
```

## BSA-SF
```{r}
betaT = rnorm(D+1); p = length(betaT)
f = function(x) -(x-1.5)^2
x = 3*runif(n*ti); ord = order(x)
w = matrix(rnorm(length(x)*(p-1)), ncol=(p-1))
u = rexp(n, lambda)
y = drop(cbind(1,w)%*%betaT + f(x) - rep(u, each=ti) + rnorm(length(x), sd=sigma))
start = as.numeric(Sys.time())
result = vbbsasf_exp(y,x,w,Z,23)
print(paste("Time elapsed :", round(as.numeric(Sys.time()-start),4), "seconds"))
```

```{r echo=FALSE,fig.align="center",fig.height=3.7,fig.width=7}
res = y-(cbind(1,w)%*%result$mubeta.q-Z%*%result$muu.q)
par(mar=c(4,4.5,2,1),mfrow=c(1,2))
plot(betaT[-1], result$mubeta.q[-1], main="Fixed effects", ylab="Estimated", xlab="True")
lines(-5:5,-5:5)
plot(u, result$muu.q, main="Random effects", ylab="Estimated", xlab="True")
lines(-1:10,-1:10)
par(mar=c(4,2,2,1),mfrow=c(1,1))
plot(x,res, main="Fitted mean curve and 95% credible region", ylab="")
lines(x[ord],result$post_curve[ord],lwd=3,col=3)
lines(x[ord],result$post_upper[ord],lwd=2,lty=2)
lines(x[ord],result$post_lower[ord],lwd=2,lty=2)
```

\newpage

# Gamma inefficiency

## Linear
```{r}
lambda = 1.5; theta = 2
set.seed(5)
betaT = rnorm(D+1)
w = matrix(rnorm(nrow(Z)*D), ncol=D)
uT = rgamma(n,shape=theta,rate=lambda)
y = drop(cbind(1,w)%*%betaT-rep(uT,each=ti)+rnorm(nrow(Z),sd=sigma))
start = as.numeric(Sys.time())
result = vbsf_gam(y,w,Z)
print(paste("Time elapsed :", round(as.numeric(Sys.time()-start),4), "seconds"))
```

```{r echo=FALSE,fig.align="center",fig.height=3.7,fig.width=7}
par(mfrow=c(1,2))
plot(betaT,result$mubeta.q,main="Fixed effect",xlab="True",ylab="Estimated")
lines(-10:10,-10:10)
plot(uT,result$muu.q,main="Inefficiency",xlab="True",ylab="Estimated")
lines(-10:10,-10:10)
```

## BSA-SF
```{r}
betaT = rnorm(D+1); p = length(betaT)
f = function(x) (x-2)^2
# data generation
x = 3*runif(n*ti); ord = order(x)
w = matrix(rnorm(length(x)*(p-1)), ncol=(p-1))
u = rgamma(n,shape=theta,rate=lambda)
y = drop(cbind(1,w)%*%betaT + f(x) - rep(u, each=ti) + rnorm(length(x), sd=sigma))
start = as.numeric(Sys.time())
result = vbbsasf_gam(y,x,w,Z,23)
print(paste("Time elapsed :", round(as.numeric(Sys.time()-start),4), "seconds"))
```

```{r echo=FALSE,fig.align="center",fig.height=3.7,fig.width=7}
res = y-(cbind(1,w)%*%result$mubeta.q-Z%*%result$muu.q)
par(mar=c(4,4.5,2,1),mfrow=c(1,2))
plot(betaT[-1], result$mubeta.q[-1], main="Fixed effects", ylab="Estimated", xlab="True")
lines(-5:5,-5:5)
plot(u, result$muu.q, main="Random effects", ylab="Estimated", xlab="True")
lines(-1:10,-1:10)
par(mar=c(4,2,2,1),mfrow=c(1,1))
plot(x,res, main="Fitted mean curve and 95% credible region", ylab="")
lines(x[ord],result$post_curve[ord],lwd=3,col=3)
lines(x[ord],result$post_upper[ord],lwd=2,lty=2)
lines(x[ord],result$post_lower[ord],lwd=2,lty=2)
```